# Generated by Django 4.0.1 on 2022-02-07 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=3)),
                ('gender', models.CharField(max_length=10)),
                ('choose', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('issues', models.CharField(blank=True, max_length=250, null=True)),
                ('posted_at', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
