# Generated by Django 4.0.1 on 2022-02-09 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_donate_age_alter_donate_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='donate_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
