# Generated by Django 4.0.1 on 2022-02-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donate_donate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='description',
        ),
    ]
