# Generated by Django 4.0.1 on 2022-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_donate_city_donate_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donate',
            options={'ordering': ['-posted_at']},
        ),
        migrations.AlterField(
            model_name='donate',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donate',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
