# Generated by Django 4.0.1 on 2022-02-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donate',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
